### ISSUE TITLE
compile error on MacOS

### ISSUE THREAD

**Issue by arademaker** [politza/pdf-tools#389]
```
-*- mode: compilation; default-directory: "~/.emacs.d/elpa/pdf-tools-20180109.1234/build/server/" -*-
Comint started at Thu May 31 14:34:19

/Users/ar/.emacs.d/elpa/pdf-tools-20180109.1234/build/server/autobuild -i /Users/ar/.emacs.d/elpa/pdf-tools-20180109.1234/
---------------------------
    Installing packages    
---------------------------
Skipping package installation (already installed)

---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=/Users/ar/.emacs.d/elpa/pdf-tools-20180109.1234/ && make -s

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes

poppler-hack.cc:88:16: error: cannot initialize a variable of type 'GooString *' with an rvalue of type 'const GooString *'
    GooString *state = a->annot->getAppearState ();
               ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
poppler-hack.cc:108:19: error: assigning to 'GooString *' from incompatible type 'const GooString *'
    text = annot->getDate ();
           ~~~~~~~^~~~~~~~~~
2 errors generated.
make[1]: *** [epdfinfo-poppler-hack.o] Error 1
make: *** [all] Error 2
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Thu May 31 14:34:25
``` 

Any idea?

**Comment by bastibe** [comment]
I get the same error. You can fix it locally, by editing your poppler-hack.cc in two places:

Line 88: change `GooString *state = a->annot->getAppearState ();` to `GooString *state = (GooString*) a->annot->getAppearState ();`
Line 108: change `text = annot->getDate ();` to `text = (GooString*) annot->getDate ();`.

**Comment by arademaker** [comment]
solved in the last version from melpa!

**Comment by dingxiangfei2009** [comment]
Build still fails on master with the same errors, @arademaker please verify.

**Comment by diego898** [comment]
I am also seeing this still

**Comment by Gonaco** [comment]
Me as well

**Comment by hyiltiz** [comment]
```
-*- mode: compilation; default-directory: "~/.emacs.d/elpa/pdf-tools-20180925.715/build/server/" -*-
Comint started at Mon Nov  5 16:09:03

/Users/hormetyiltiz/.emacs.d/elpa/pdf-tools-20180925.715/build/server/autobuild -i /Users/me/.emacs.d/elpa/pdf-tools-20180925.715/
---------------------------
    Installing packages    
---------------------------
Skipping package installation (already installed)

---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=/Users/me/.emacs.d/elpa/pdf-tools-20180925.715/ && make -s

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes

ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: ignoring file libsynctex.a, file was built for archive which is not the architecture being linked (x86_64): libsynctex.a
Undefined symbols for architecture x86_64:
  "_synctex_display_query", referenced from:
      _cmd_synctex_forward_search in epdfinfo-epdfinfo.o
  "_synctex_edit_query", referenced from:
      _cmd_synctex_backward_search in epdfinfo-epdfinfo.o
  "_synctex_next_result", referenced from:
      _cmd_synctex_forward_search in epdfinfo-epdfinfo.o
      _cmd_synctex_backward_search in epdfinfo-epdfinfo.o
  "_synctex_node_box_visible_depth", referenced from:
      _cmd_synctex_forward_search in epdfinfo-epdfinfo.o
  "_synctex_node_box_visible_h", referenced from:
      _cmd_synctex_forward_search in epdfinfo-epdfinfo.o
  "_synctex_node_box_visible_height", referenced from:
      _cmd_synctex_forward_search in epdfinfo-epdfinfo.o
  "_synctex_node_box_visible_v", referenced from:
      _cmd_synctex_forward_search in epdfinfo-epdfinfo.o
  "_synctex_node_box_visible_width", referenced from:
      _cmd_synctex_forward_search in epdfinfo-epdfinfo.o
  "_synctex_node_column", referenced from:
      _cmd_synctex_backward_search in epdfinfo-epdfinfo.o
  "_synctex_node_line", referenced from:
      _cmd_synctex_backward_search in epdfinfo-epdfinfo.o
  "_synctex_node_page", referenced from:
      _cmd_synctex_forward_search in epdfinfo-epdfinfo.o
  "_synctex_node_tag", referenced from:
      _cmd_synctex_backward_search in epdfinfo-epdfinfo.o
  "_synctex_scanner_free", referenced from:
      _cmd_synctex_forward_search in epdfinfo-epdfinfo.o
      _cmd_synctex_backward_search in epdfinfo-epdfinfo.o
  "_synctex_scanner_get_name", referenced from:
      _cmd_synctex_backward_search in epdfinfo-epdfinfo.o
  "_synctex_scanner_new_with_output_file", referenced from:
      _cmd_synctex_forward_search in epdfinfo-epdfinfo.o
      _cmd_synctex_backward_search in epdfinfo-epdfinfo.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:471: epdfinfo] Error 1
make: *** [Makefile:366: all] Error 2
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Mon Nov  5 16:09:11
```
