### ISSUE TITLE
pdf-tools-install cannot find poppler

### ISSUE THREAD

**Issue by esrztk** [politza/pdf-tools#679]
Hi,

I'm trying to install pdf-tools on Mac OS however keep getting `No package 'poppler' found` error.

I've tried using other PKG_CONFIG_PATH solutions but they do not work.

`---------------------------
    Installing packages    
---------------------------
brew install pkg-config poppler automake
Warning: pkg-config 0.29.2_3 is already installed and up-to-date.
To reinstall 0.29.2_3, run:
  brew reinstall pkg-config
Warning: poppler 21.06.1 is already installed and up-to-date.
To reinstall 21.06.1, run:
  brew reinstall poppler
Warning: automake 1.16.3_1 is already installed and up-to-date.
To reinstall 1.16.3_1, run:
  brew reinstall automake

---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=~/.emacs.d/elpa/pdf-tools-0.90/ && make -s
configure: error: Package requirements (poppler) were not met:

No package 'poppler' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables poppler_CFLAGS
and poppler_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.`

**Comment by asrosenberg** [comment]
pdf-tools-20210531.1613
Emacs 27.2
Pop_os 21.04

I am having the same issue on Pop_os 21.04. It seems like every so often there is an incompatibility issue between poppler and pdf-tools:

---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=/home/andrew/.emacs.d/elpa/pdf-tools-20210531.1613/ && make clean && make -s
configure: error: Package requirements (poppler) were not met:

Package 'poppler', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables poppler_CFLAGS
and poppler_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Sun Aug  1 11:31:35

**Comment by LvanderGoten** [comment]
I found out that these problems can sometimes be resolved by **not** running these commands from Emacs, i.e. by running 
`~/.emacs.d/.local/straight/build-27.2/pdf-tools/build/server/autobuild -i ~/.emacs.d/.local/straight/build-27.2/pdf-tools/` from your terminal.

**Comment by asrosenberg** [comment]
Thanks for the reply! It's still throwing: configure: error: cannot find necessary  poppler-private header (see README.org)

I have all of the dependencies installed.

**Comment by jonathanabennett** [comment]
I'm also having the same issue, exact same error as @JunHoo-Lee.
M1 MacBook Big Sur 11.6
Emacs 28.50
Doom emacs config

I've tried it from within Emacs and directly from the command line as suggested by @LvanderGoten, same error message. It cannot find poppler.

**Comment by vedang** [comment]
This package is no longer maintained. The maintained fork is `vedang/pdf-tools`. Please download the latest `pdf-tools` from there and try again. If you are still seeing the error, please open a new issue there so that I can track it and fix it. Please close this issue.

**Comment by jonathanabennett** [comment]
Have doom-emacs or MELPA been updated?

**Comment by vedang** [comment]
Yes, both have been updated a few months ago.
